INSERT INTO `optica_DB`.`tipos_de_cristales`(`cristal_tipo`)
VALUES 
	(`Org. blanco`),
	(`Org. AR`),
    (`Org. BLC`),    
    (`Org. BLC + AR`),
    (`Org. Foto`),
	(`Org. Foto + AR`),
    (`Policarbonato Blanco`),
    (`Policarbonato AR`),
    (`Policarbonato BLC + AR`),
    (`Mineral Blanco`),
    (`Mineral Blanco + AR`),
    (`Mineral BLC`),
    (`Mineral BLC + AR`),
	(`Mineral Foto`),
    (`Mineral Foto + AR`),
    (`Bifocal Flat top Org. Blanco`),
    (`Bifocal Flat top Org. Blanco + AR`),
    (`Bifocal Flat top Org. BLC`),
    (`Bifocal Flat top Org. BLC + AR`),
    (`Bifocal Flat top Org. Foto`),
    (`Bifocal Flat top Org. Foto + AR`),    
    (`Multifocal Easy Org. Blanco`),
    (`Multifocal Easy Org. Blanco + AR`),
    (`Multifocal Easy Org. BLC`),
    (`Multifocal Easy Org. BLC + AR`);